### ISSUE TITLE
The access token is not displayed correctly in confirmation emails

### ISSUE THREAD

**Issue by zadigus** [jelastic-jps/kubernetes#52]
After installing version v1.25.4, here's how the confirmation email looks like:

![image](https://user-images.githubusercontent.com/8761254/216046359-6d5bf50b-b276-4fee-b881-56eeac5d4b9c.png)

There seems to be an issue with the rendering of the access token, as you can see.

**Comment by dfateyev** [comment]
Please provide more information on the installation method that you've used.
Is it the installation via the platform Marketplace, or via a JPS manifest, or something else?

**Comment by zadigus** [comment]
When I install the manifest of kubernetes from branch v1.25.4, then the token doesn't display correctly in the confirmation email. When I install kubernetes from the marketplace the token looks good in the confirmation email (though I'd have to try again to be sure). I am using jelastic v8.1.1.

**Comment by zadigus** [comment]
I have deployed the k8s cluster this morning in two different ways:

* through the install method documented [here](https://docs.jelastic.com/api/#!/api/marketplace.Jps) and with [this manifest](https://github.com/jelastic-jps/kubernetes/blob/v1.25.4/manifest.jps): in the email, the token is displayed as I showed in my initial post, i.e. with html tags
* through the marketplace in the jelastic dashboard, with version 1.25.4: the token is displayed nicely in the confirmation email

**Comment by dfateyev** [comment]
It is the expected behavior for the manifests installed not from the platform Marketplace.
For the security reasons, some of visual elements and functionality are restricted for external manifests, that are installed via API or in Dashboard (via "Import" option).
To get the behavior, provided by native Marketplace manifests, you need to publish the manifest to the platform's  Marketplace.
